## Multiple Linear Regression

In [99]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

from sklearn.linear_model import LinearRegression

In [100]:
data = pd.read_csv('Multiple-linear-regression.csv')
data.head()

SAT  Rand 1,2,3   GPA
0  1714           1  2.40
1  1664           3  2.52
2  1760           3  2.54
3  1685           3  2.74
4  1693           2  2.83

In [101]:
data.describe()

SAT  Rand 1,2,3        GPA
count    84.000000   84.000000  84.000000
mean   1845.273810    2.059524   3.330238
std     104.530661    0.855192   0.271617
min    1634.000000    1.000000   2.400000
25%    1772.000000    1.000000   3.190000
50%    1846.000000    2.000000   3.380000
75%    1934.000000    3.000000   3.502500
max    2050.000000    3.000000   3.810000

#### Declare the independent and dependent variables

In [102]:
x = data[['SAT', 'Rand 1,2,3']]
y = data['GPA']

#### Standardization

In [103]:
from sklearn.preprocessing import StandardScaler

In [104]:
scaler = StandardScaler()

In [105]:
scaler.fit(x) #scaling mechanism that will be used to scale our data

StandardScaler()

In [106]:
x_scaled = scaler.transform(x)

In [107]:
x_scaled

array([[-1.26338288, -1.24637147],
       [-1.74458431,  1.10632974],
       [-0.82067757,  1.10632974],
       [-1.54247971,  1.10632974],
       [-1.46548748, -0.07002087],
       [-1.68684014, -1.24637147],
       [-0.78218146, -0.07002087],
       [-0.78218146, -1.24637147],
       [-0.51270866, -0.07002087],
       [ 0.04548499,  1.10632974],
       [-1.06127829,  1.10632974],
       [-0.67631715, -0.07002087],
       [-1.06127829, -1.24637147],
       [-1.28263094,  1.10632974],
       [-0.6955652 , -0.07002087],
       [ 0.25721362, -0.07002087],
       [-0.86879772,  1.10632974],
       [-1.64834403, -0.07002087],
       [-0.03150724,  1.10632974],
       [-0.57045283,  1.10632974],
       [-0.81105355,  1.10632974],
       [-1.18639066,  1.10632974],
       [-1.75420834,  1.10632974],
       [-1.52323165, -1.24637147],
       [ 1.23886453, -1.24637147],
       [-0.18549169, -1.24637147],
       [-0.5608288 , -1.24637147],
       [-0.23361183,  1.10632974],
       [ 1.68156984,


#### Create the regression

In [108]:
reg = LinearRegression()
reg.fit(x_scaled,y)

LinearRegression()

In [109]:
reg.coef_

array([ 0.17181389, -0.00703007])

In [110]:
reg.intercept_

3.330238095238095

#### Creating a Summary Table

In [111]:
reg_summary = pd.DataFrame(['Bias','SAT','Rand 1,2,3'], columns=['Features']) #intercept is known as 'bias'
reg_summary['Weights'] = reg.intercept_,reg.coef_[0], reg.coef_[1] #the bigger the weight, the bigger the impact

In [112]:
reg_summary 

Features   Weights
0        Bias  3.330238
1         SAT  0.171814
2  Rand 1,2,3 -0.007030

#### Making Predictions Using the Standardised Coefficients

In [113]:
new_data = pd.DataFrame(data =[[1700,2],[1800,1]], columns=['SAT','Rand 1,2,3'])
new_data

SAT  Rand 1,2,3
0  1700           2
1  1800           1

In [114]:
new_data_scaled = scaler.transform(new_data)
new_data_scaled

array([[-1.39811928, -0.07002087],
       [-0.43571643, -1.24637147]])

In [115]:
reg.predict(new_data_scaled)

array([3.09051403, 3.26413803])

#### What if we removed the Rand 1,2,3 feature?

In [117]:
reg_simple = LinearRegression()

x_simple_matrix = x_scaled[:,0].reshape(-1,1)
reg_simple.fit(x_simple_matrix,y)

LinearRegression()

In [119]:
reg_simple.predict(new_data_scaled[:,0].reshape(-1,1))

array([3.08970998, 3.25527879])

In [120]:
#the results are basically the same